name: SupremeChat-Fork
version: '${project.version}'
main: net.devscape.project.supremechat.SupremeChat
api-version: 1.13
authors: [DevScape, TremeQu]

commands:
  supremechat:
    aliases: [schat, sc]
  channel:
    aliases: [c, channels]
  emojis:
    description: 'List all available emojis.'
    aliases: [emoji]
    permission: 'supremechat.emojis'